<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ruowen Xiao">
<meta name="dcterms.date" content="2026-05-12">

<title>Statistical Tests</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Lab3_student_report_files/libs/clipboard/clipboard.min.js"></script>
<script src="Lab3_student_report_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Lab3_student_report_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Lab3_student_report_files/libs/quarto-html/popper.min.js"></script>
<script src="Lab3_student_report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Lab3_student_report_files/libs/quarto-html/anchor.min.js"></script>
<link href="Lab3_student_report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Lab3_student_report_files/libs/quarto-html/quarto-syntax-highlighting-f81f3c79f694eaf6f88ebcce70241f9e.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Lab3_student_report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Lab3_student_report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Lab3_student_report_files/libs/bootstrap/bootstrap-d6b8d44ecd6326bb9553a87133ad9872.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#preparation-tasks" id="toc-preparation-tasks" class="nav-link active" data-scroll-target="#preparation-tasks">Preparation Tasks</a></li>
  <li><a href="#basic-concepts-in-hypothesis-testing" id="toc-basic-concepts-in-hypothesis-testing" class="nav-link" data-scroll-target="#basic-concepts-in-hypothesis-testing">1. Basic Concepts in Hypothesis Testing</a></li>
  <li><a href="#test-power-and-power-function" id="toc-test-power-and-power-function" class="nav-link" data-scroll-target="#test-power-and-power-function">2. Test Power and Power Function</a>
  <ul class="collapse">
  <li><a href="#answer-to-the-example-with-dry-mouth" id="toc-answer-to-the-example-with-dry-mouth" class="nav-link" data-scroll-target="#answer-to-the-example-with-dry-mouth">Answer to the example with dry mouth</a></li>
  </ul></li>
  <li><a href="#test-of-population-mean-t-test" id="toc-test-of-population-mean-t-test" class="nav-link" data-scroll-target="#test-of-population-mean-t-test">3. Test of Population Mean (t-test)</a></li>
  <li><a href="#comparison-of-means-in-two-populations-t-test-for-two-independent-samples" id="toc-comparison-of-means-in-two-populations-t-test-for-two-independent-samples" class="nav-link" data-scroll-target="#comparison-of-means-in-two-populations-t-test-for-two-independent-samples">4. Comparison of Means in Two Populations (t-test for Two Independent Samples)</a></li>
  <li><a href="#test-with-matched-data-paired-samples" id="toc-test-with-matched-data-paired-samples" class="nav-link" data-scroll-target="#test-with-matched-data-paired-samples">5. Test with Matched Data (Paired Samples)</a>
  <ul class="collapse">
  <li><a href="#answers-to-some-of-the-questions-in-this-section" id="toc-answers-to-some-of-the-questions-in-this-section" class="nav-link" data-scroll-target="#answers-to-some-of-the-questions-in-this-section">Answers to Some of the Questions in This Section:</a></li>
  </ul></li>
  <li><a href="#had-our-activation-program-an-effect" id="toc-had-our-activation-program-an-effect" class="nav-link" data-scroll-target="#had-our-activation-program-an-effect">6. Had our activation program an effect?</a>
  <ul class="collapse">
  <li><a href="#problem-specification-in-the-study" id="toc-problem-specification-in-the-study" class="nav-link" data-scroll-target="#problem-specification-in-the-study">Problem specification in the study</a></li>
  <li><a href="#questions" id="toc-questions" class="nav-link" data-scroll-target="#questions">Questions</a></li>
  <li><a href="#instruction-for-reporting" id="toc-instruction-for-reporting" class="nav-link" data-scroll-target="#instruction-for-reporting">Instruction for reporting</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="Lab3_student_report.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li><li><a href="Lab3_student_report.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Statistical Tests</h1>
<p class="subtitle lead">Computer Lab 3</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Ruowen Xiao </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 12, 2026</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    <p>The purpose of today’s lab is for you to:</p>
    <ul>
    <li>practice the basic concepts of hypothesis testing (e.g., significance level and power) and what conclusions can be drawn from the analysis</li>
    <li>familiarize yourself with some of the functions available in R regarding various basic statistical tests</li>
    <li>practice constructing a reasonable statistical model using collected data, as well as critically reviewing the model and its ability to describe reality</li>
    <li>apply your knowledge and analyse a biostatistical dataset using R</li>
    <li>practice presenting assumptions, models, and conclusions from a statistical analysis in writing</li>
    </ul>
  </div>
</div>


</header>


<section id="preparation-tasks" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="preparation-tasks">Preparation Tasks</h2>
<blockquote class="blockquote">
<p>Review the concepts of <em>hypotheses, significance level, power function,</em> and <em>model with matched data and model with two independent samples</em>.</p>
<p>You should have completed the following tasks <em>before</em> you come to the lab.</p>
</blockquote>
<div class="callout callout-style-default callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Homework 1
</div>
</div>
<div class="callout-body-container callout-body">
<p>To practice the basic concepts in hypothesis testing, complete exercises <strong>Dig:4.4.1(error rates)_3, _4, and _5 in exercise 7</strong>.</p>
</div>
</div>
<div class="callout callout-style-default callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Homework 2
</div>
</div>
<div class="callout-body-container callout-body">
<p>To practice different models, do <strong>Dig:5.2_1 and _2</strong>.</p>
</div>
</div>
<div class="callout callout-style-default callout-warning no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>Before You Start
</div>
</div>
<div class="callout-body-container callout-body">
<p>Load R functions needed for the lab. These functions come from the R package <strong>Räkna med variation</strong>, but to avoid installation problems, we have extracted the ones you will use and saved them in a file. You “inform” R that these functions exist by running the following code:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"kod/funktioner_raknamedvariation_light.R"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</section>
<section id="basic-concepts-in-hypothesis-testing" class="level1 unnumbered">
<h1 class="unnumbered">1. Basic Concepts in Hypothesis Testing</h1>
<blockquote class="blockquote">
<p>Medication can reduce salivary gland function, which is a risk factor for cavities and other oral diseases. Saliva stimulated by chewing was measured for 5 minutes in 7 randomly selected patients, all receiving the same medication. The normal saliva amount under these conditions is 1 ml/min, and dry mouth is considered when the saliva amount is below 0.7 ml/min. The model assumed that the saliva amount is normally distributed with mean <span class="math inline">\(\mu\)</span> and standard deviation <span class="math inline">\(\sigma\)</span>, where <span class="math inline">\(\sigma\)</span> is considered to be 0.5 ml/min. Interesting questions include:</p>
<ul>
<li>Do the data support our suspicion that the medication lowers saliva production?</li>
<li>If the medication results in an average saliva production of 0.8 ml/min, how likely are we to miss the reduced saliva production with our test?</li>
<li>How many patients should we measure if we want the test to detect reduced saliva production at 0.7 ml/min with a probability of 0.95?</li>
</ul>
<p>On the course website, you will find data in the file <code>saliv.RData</code>. Concise answers to the questions posed in the tasks are provided at the end of this part of the guide.</p>
</blockquote>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Task 1.1
</div>
</div>
<div class="callout-body-container callout-body">
<p>First, we want to investigate if the data from the 7 patients support our suspicion that the medication lowers saliva production. Set up a model and appropriate hypotheses.</p>
</div>
</div>
<p><strong>Model</strong>: We assume that the saliva amount follows a normal distribution: <span class="math display">\[x \sim N(\mu, \sigma),\]</span> where <span class="math inline">\(\sigma = 0.5 \text{ml/min}.\)</span></p>
<p><strong>Hypotheses</strong>:</p>
<ul>
<li><span class="math inline">\(H_0: \mu = 1\)</span></li>
<li><span class="math inline">\(H_1: \mu &lt; 1\)</span></li>
</ul>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Task 1.2
</div>
</div>
<div class="callout-body-container callout-body">
<p>Calculate the mean of the measurements.</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"./data/lab3_filer/saliv.RData"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>mean_saliva <span class="ot">&lt;-</span> <span class="fu">mean</span>(salivprod)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Answer</strong>: The mean of measurements is 0.65 ml/min.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Task 1.3
</div>
</div>
<div class="callout-body-container callout-body">
<p>Use the routine <code>hypotes</code> to illustrate the test’s critical region when the test is performed at a significance level of <span class="math inline">\(\alpha = 0.05\)</span>. The relevant command is <code>hypotes(</code><span class="math inline">\(\sigma\)</span>, <span class="math inline">\(n\)</span>, <span class="math inline">\(\mu_0\)</span>, <span class="math inline">\(\alpha\)</span>, <code>H1-direction)</code>. With hypotheses <span class="math inline">\(H_0: \mu = 1\)</span> and <span class="math inline">\(H_1: \mu &lt; 1\)</span>, the command becomes <code>hypotes(0.5, 7, 1, 0.05, '&lt;')</code>. Use the routine with the hypotheses you have formulated. (Ignore any error messages that may occur and look at the figure.)</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>sigma <span class="ot">&lt;-</span> <span class="fl">0.5</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">7</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>mu0 <span class="ot">&lt;-</span> <span class="dv">1</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">hypotes</span>(sigma, n, mu0, alpha, <span class="st">'&lt;'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab3_student_report_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Task 1.4
</div>
</div>
<div class="callout-body-container callout-body">
<p>The routine marks the critical region and provides a value <span class="math inline">\(k\)</span> which is the boundary of the region. How has <span class="math inline">\(k\)</span> been calculated? Set up the mathematical formula for <span class="math inline">\(k\)</span> and use it to calculate <span class="math inline">\(k\)</span> yourself.</p>
</div>
</div>
<p><strong>Equation for <span class="math inline">\(k\)</span></strong>: <span class="math display">\[k = \mu_0 - \lambda_{\alpha} \frac{\sigma}{\sqrt{n}}\]</span></p>
<p><strong>Own calculation of <span class="math inline">\(k\)</span></strong>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> mu0 <span class="sc">-</span> <span class="fu">qnorm</span>(<span class="dv">1</span> <span class="sc">-</span> alpha) <span class="sc">*</span> sigma <span class="sc">/</span> <span class="fu">sqrt</span>(n)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><span class="math inline">\(k = 0.69\)</span></p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Task 1.5
</div>
</div>
<div class="callout-body-container callout-body">
<p>Use your calculated sample mean to conduct the test. What is your conclusion about the null hypothesis, <span class="math inline">\(H_0\)</span>?</p>
</div>
</div>
<p><strong>Answer:</strong> <span class="math inline">\(H_0\)</span> is rejected since <span class="math inline">\(\bar x &lt; k\)</span>.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Task 1.6
</div>
</div>
<div class="callout-body-container callout-body">
<p>What is your concrete interpretation of the significance level <span class="math inline">\(\alpha = 0.05\)</span> in this example?</p>
</div>
</div>
<p><strong>Answer:</strong> <span class="math inline">\(\alpha\)</span> is the probability of type I error, which means there is 5% probability of rejecting <span class="math inline">\(H_0\)</span> even though it’s true. In this case, there is a 5% risk that we conclude the medication lowers saliva production while it actually doesn’t.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Task 1.7
</div>
</div>
<div class="callout-body-container callout-body">
<p>Examine how the critical region changes when you change the significance level to <span class="math inline">\(\alpha = 0.01\)</span>. What is your conclusion now?</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.01</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hypotes</span>(sigma, n, mu0, alpha, <span class="st">'&lt;'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab3_student_report_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>alpha <span class="ot">&lt;-</span> <span class="fl">0.05</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p><strong>Answer:</strong> When the significance level decreased to <span class="math inline">\(0.01\)</span>, the sample mean is not in the critical area. We can conclude that <span class="math inline">\(H_0\)</span> is not rejected and the medication doesn’t lower saliva production.</p>
</section>
<section id="test-power-and-power-function" class="level1 unnumbered">
<h1 class="unnumbered">2. Test Power and Power Function</h1>
<blockquote class="blockquote">
<p>Now assume that the average saliva secretion in the risk group is 0.8. Then, of course, <span class="math inline">\(H_0: \mu = 1\)</span> is false, and we want our test to detect this and reject this hypothesis in favor of the hypothesis <span class="math inline">\(H_1: \mu &lt; 1\)</span>. The probability that the test actually accomplishes this is called the test power at the point 0.8. Use the routine <code>hypotes</code> to illustrate the test power at the point 0.8. The command now is <code>hypotes(</code><span class="math inline">\(\sigma\)</span>, <span class="math inline">\(n\)</span>, <span class="math inline">\(\mu_0\)</span>, <span class="math inline">\(\alpha\)</span>, H1-direction, true <span class="math inline">\(\mu\)</span><code>), so in this case, you write</code>hypotes(0.5, 7, 1, 0.05, ‘&lt;’, 0.8)`.</p>
</blockquote>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>mu_true <span class="ot">&lt;-</span> <span class="fl">0.8</span> </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hypotes</span>(sigma, n, mu0, alpha, <span class="st">'&lt;'</span>, mu_true)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab3_student_report_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Task 2.1
</div>
</div>
<div class="callout-body-container callout-body">
<p>The routine gives you another figure which, besides the significance level <span class="math inline">\(\alpha\)</span> (type I error risk), also shows <span class="math inline">\(\beta\)</span> (type II error risk). What is the concrete interpretation of <span class="math inline">\(\beta\)</span> in this example? How does <span class="math inline">\(\beta\)</span> relate to the test power?</p>
<p>Generally, the test power at the point <span class="math inline">\(\mu\)</span> is the probability that the null hypothesis is rejected given that <span class="math inline">\(\mu\)</span> is the true average saliva secretion in the risk group, i.e.,</p>
<p><span class="math display">\[
S(\mu)=P(\text{reject } H_0 | \mu)
\]</span></p>
<p>Note that the power depends on the value of <span class="math inline">\(\mu\)</span>. In this example, the smaller <span class="math inline">\(\mu\)</span> is relative to <span class="math inline">\(\mu_0= 1\)</span>, the greater the chance that the test will detect that <span class="math inline">\(H_0\)</span> is not true. Therefore, it is interesting to study the power as a function of <span class="math inline">\(\mu\)</span>, and this function is often denoted <span class="math inline">\(S(\mu)\)</span>.</p>
<p>The command <code>styrka(0.5, 7, 1, 0.05, '&lt;', 0.8)</code> gives you the previous figure plus the power as a function of <span class="math inline">\(\mu\)</span>.</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">styrka</span>(sigma, n, mu0, alpha, <span class="st">'&lt;'</span>, mu_true)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab3_student_report_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p><strong>Answer:</strong> <span class="math inline">\(\beta\)</span> is the probability of type II error, not rejecting <span class="math inline">\(H_0\)</span> when <span class="math inline">\(H_1\)</span> is true. In this example, <span class="math inline">\(\beta\)</span> is the probability that we conclude the medication doesn’t lower saliva production even though it does. The test power is <span class="math inline">\(1 - \beta\)</span>.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Task 2.2
</div>
</div>
<div class="callout-body-container callout-body">
<p>Based on the power function, estimate the probability that with our test, we will detect that a group that should be classified as having dry mouth (<span class="math inline">\(\mu= 0.7\)</span>) has reduced saliva production.</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>mu_true <span class="ot">&lt;-</span> <span class="fl">0.7</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">styrka</span>(sigma, n, mu0, alpha, <span class="st">'&lt;'</span>, mu_true)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab3_student_report_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Answer:</strong> The probability of detecting reduced saliva production with dry mouth is <span class="math inline">\(48%\)</span>.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Task 2.3
</div>
</div>
<div class="callout-body-container callout-body">
<p>How many patients should we measure if we want to have a 0.95 probability of detecting that individuals with dry mouth have reduced saliva production? Hint: Try different values of <span class="math inline">\(n\)</span> in <code>styrkefkn</code>.</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">30</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">styrka</span>(sigma, n, mu0, alpha, <span class="st">'&lt;'</span>, mu_true)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab3_student_report_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Answer:</strong> If we want to have a 95% probability of dectecting that individuals with dry mouth have reduced saliva production, we should measure at least 30 patients.</p>
<section id="answer-to-the-example-with-dry-mouth" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="answer-to-the-example-with-dry-mouth">Answer to the example with dry mouth</h2>
<ol type="1">
<li>Part 1<br>
1.1 <span class="math inline">\(H_0: \mu = 1\)</span>; <span class="math inline">\(H_1: \mu &lt; 1\)</span><br>
1.2 <span class="math inline">\(k=\mu_0 - z_{1-\alpha}\, \frac{\sigma}{\sqrt{n}} =  1-1.6445 \cdot \frac{0.05}{\sqrt{7}}=0.689\)</span><br>
1.5 Since the mean is <span class="math inline">\(&lt; 0.689\)</span>, <span class="math inline">\(H_0\)</span> is rejected at the 0.05 level<br>
1.6 There is a 5% chance that we claim a person in the risk group has reduced saliva production when it is actually normal 1.7 <span class="math inline">\(H_0\)</span> cannot be rejected at the 0.01 level</li>
<li>Part 2<br>
2.1 <span class="math inline">\(\beta = P(\text{not reject } H_0|\mu)\)</span>, i.e., <span class="math inline">\(\beta\)</span> when the true expected value is 0.8 is 1 minus the power at the point 0.8 = 1- S(0.8)<br>
2.2 The power at the point 0.7, S(0.7), can be estimated as 0.48 according to the figure<br>
2.3 <span class="math inline">\(n=30\)</span> patients are required for the power to be 0.95 at the point 0.7</li>
</ol>
</section>
</section>
<section id="test-of-population-mean-t-test" class="level1 unnumbered">
<h1 class="unnumbered">3. Test of Population Mean (t-test)</h1>
<blockquote class="blockquote">
<p>A mixture of blood serum contains exactly 42 g of albumin per liter. Two laboratories (A and B) make six determinations each of the concentration. We want to investigate if there is any systematic deviation from the true value (42 g/l) in each of these two groups.</p>
</blockquote>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"data/lab3_filer/albumin.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Exercise 3.1
</div>
</div>
<div class="callout-body-container callout-body">
<p>Specify the model for A and B and specify hypotheses to test if there is a systematic deviation from the true value in each group. Hint: it should be a two-sided alternative hypothesis.</p>
</div>
</div>
<p><strong>Model for group A:</strong> Let <span class="math inline">\(X\)</span> be the concentration of g of albumin per liter in measurements from laboratory A. The mean and variance for <span class="math inline">\(X\)</span> are <span class="math inline">\(\mu_x\)</span> and <span class="math inline">\(\sigma^2_x\)</span>. Assume that measurements are independent and identically distributed. The mean is estimated by the sample mean <span class="math inline">\(\hat{\mu}_x=\bar{x}\)</span>. According to the central limit theorem, <span class="math inline">\(\bar{x} \overset{A}{\sim} N(\mu_x,\frac{\sigma_x}{\sqrt{n_x}})\)</span>.</p>
<p><strong>Hypotheses for group A:</strong></p>
<ul>
<li><span class="math inline">\(H_0: \bar x = 42\)</span></li>
<li><span class="math inline">\(H_1: \bar x \neq 42\)</span></li>
</ul>
<p><strong>Model for group B:</strong> Let <span class="math inline">\(Y\)</span> be the concentration of g of albumin per liter in measurements from laboratory B. The mean and variance for <span class="math inline">\(Y\)</span> are <span class="math inline">\(\mu_y\)</span> and <span class="math inline">\(\sigma^2_y\)</span>. Assume that measurements are independent and identically distributed. The mean is estimated by the sample mean <span class="math inline">\(\hat{\mu}_y=\bar{y}\)</span>. According to the central limit theorem, <span class="math inline">\(\bar{y} \overset{A}{\sim} N(\mu_y,\frac{\sigma_y}{\sqrt{n_y}})\)</span>.</p>
<p><strong>Hypotheses for group B:</strong></p>
<ul>
<li><span class="math inline">\(H_0: \bar y = 42\)</span></li>
<li><span class="math inline">\(H_1: \bar y \neq 42\)</span></li>
</ul>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Exercise 3.2
</div>
</div>
<div class="callout-body-container callout-body">
<p>In R, perform these two t-tests using the following routine <code>t-test</code>. Interpret the outputs when you run the command. What are the p-values and what are the conclusions for each group? What are the confidence intervals for the expected concentrations?</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(AlbuminA, <span class="at">mu=</span><span class="dv">42</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  AlbuminA
t = 2.9194, df = 5, p-value = 0.03304
alternative hypothesis: true mean is not equal to 42
95 percent confidence interval:
 42.05974 42.94026
sample estimates:
mean of x 
     42.5 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(AlbuminB, <span class="at">mu=</span><span class="dv">42</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  AlbuminB
t = -2.1843, df = 5, p-value = 0.08067
alternative hypothesis: true mean is not equal to 42
95 percent confidence interval:
 35.68716 42.51284
sample estimates:
mean of x 
     39.1 </code></pre>
</div>
</div>
<p><strong>Answer:</strong></p>
<ul>
<li>For group A, the p-value is <span class="math inline">\(0.03304\)</span>, which is less than <span class="math inline">\(0.05\)</span>. Therefore, <span class="math inline">\(H_0\)</span> is rejected. The 95% confidence interval is <span class="math inline">\([42.05974, 42.94026]\)</span>.</li>
<li>For group B, the p-value is <span class="math inline">\(0.08067\)</span>, which is greater than <span class="math inline">\(0.05\)</span>. Therefore, <span class="math inline">\(H_0\)</span> cannot be rejected. The 95% confidence interval is <span class="math inline">\([35.68716, 42.51284]\)</span>.</li>
</ul>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Exercise 3.3
</div>
</div>
<div class="callout-body-container callout-body">
<p>Suppose we want to investigate if <strong>laboratory B</strong> underestimates or overestimates concentrations. In R, this is done as a one-sided test using the routine <code>t-test</code>.</p>
<p>Interpret the output for the one-sided test for laboratory B. What happens to the p-values and intervals when moving from one-sided to two-sided alternatives?</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(AlbuminB, <span class="at">mu=</span><span class="dv">42</span>, <span class="at">alternative=</span><span class="st">"less"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  AlbuminB
t = -2.1843, df = 5, p-value = 0.04034
alternative hypothesis: true mean is less than 42
95 percent confidence interval:
     -Inf 41.77529
sample estimates:
mean of x 
     39.1 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(AlbuminB, <span class="at">mu=</span><span class="dv">42</span>, <span class="at">alternative=</span><span class="st">"greater"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  AlbuminB
t = -2.1843, df = 5, p-value = 0.9597
alternative hypothesis: true mean is greater than 42
95 percent confidence interval:
 36.42471      Inf
sample estimates:
mean of x 
     39.1 </code></pre>
</div>
</div>
<p><strong>Answer:</strong> For <span class="math inline">\(H_1: \bar y &lt; 42\)</span>, the p-value is <span class="math inline">\(0.04034\)</span> and the 95% confidence interval is <span class="math inline">\([-\infty, 41.77529]\)</span>. <span class="math inline">\(H_0\)</span> is rejected. For <span class="math inline">\(H_1: \bar y &gt; 42\)</span>, the p-value of <span class="math inline">\(0.9597\)</span> is much greater than <span class="math inline">\(0.05\)</span> and the 95% confidence interval is <span class="math inline">\([36.42471, \infty]\)</span>. We fail to reject <span class="math inline">\(H_0\)</span>. When moving from one-sided to two-sided alternatives, the p-value apporximately doubles and the confidence interval gets wider.</p>
</section>
<section id="comparison-of-means-in-two-populations-t-test-for-two-independent-samples" class="level1 unnumbered">
<h1 class="unnumbered">4. Comparison of Means in Two Populations (t-test for Two Independent Samples)</h1>
<blockquote class="blockquote">
<p>Algae were allowed to grow under light and dark conditions, and then the chlorophyll content was measured.</p>
</blockquote>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"data/lab3_filer/alger.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Exercise 4.1
</div>
</div>
<div class="callout-body-container callout-body">
<p>Make a graphical description of the differences. What does the boxplot show?</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(Alger<span class="sc">$</span>Klorofyll <span class="sc">~</span> Alger<span class="sc">$</span>Grupp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab3_student_report_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Answer:</strong> The mean chlorophyll content of the group under light is around 13 and the values range from 11-14 , while the mean value of the group under dark is around 19 and the values range from 16-24. The group under light has a smaller mean value of chlorophyll content and has a lower variability than the group under dark.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Exercise 4.2
</div>
</div>
<div class="callout-body-container callout-body">
<p>Set up the model and hypotheses, and investigate with a t-test if there are differences in the expected chlorophyll content between the two groups.</p>
<p>This can be done by adding the group variable in the <code>t.test</code> routine. Interpret the output.</p>
</div>
</div>
<p><strong>Model:</strong> Let <span class="math inline">\(X\)</span> be the growth of algae in dark conditions with mean <span class="math inline">\(\mu_x\)</span> and variance <span class="math inline">\(\sigma^2_x\)</span>, and <span class="math inline">\(Y\)</span> be the growth of algae in light conditions with mean <span class="math inline">\(\mu_y\)</span> and variance <span class="math inline">\(\sigma^2_y\)</span>. The means are estimated by sample means <span class="math inline">\(\hat{\mu_x}=\bar{x}\)</span> and <span class="math inline">\(\hat{\mu_y}=\bar{y}\)</span>. According to the central limit theorem, the estimation of each mean will be approximately normally distributed, i.e., <span class="math inline">\(\bar{x} \overset{A}{\sim} N(\mu_x,\frac{\sigma_x}{\sqrt{n_x}})\)</span> and <span class="math inline">\(\bar{y} \overset{A}{\sim} N(\mu_y,\frac{\sigma_y}{\sqrt{n_y}})\)</span>.</p>
<p><strong>Hypotheses:</strong> <span class="math inline">\(H_0: \mu_x = \mu_y\)</span> vs.&nbsp;<span class="math inline">\(H_1: \mu_x \neq \mu_y\)</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Alger<span class="sc">$</span>Klorofyll <span class="sc">~</span> Alger<span class="sc">$</span>Grupp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  Alger$Klorofyll by Alger$Grupp
t = -3.2089, df = 9.0652, p-value = 0.01058
alternative hypothesis: true difference in means between group Ljus and group Mörker is not equal to 0
95 percent confidence interval:
 -11.219229  -1.947438
sample estimates:
  mean in group Ljus mean in group Mörker 
            13.10000             19.68333 </code></pre>
</div>
</div>
<p><strong>Answer:</strong> The p-value of this two sample t-test is <span class="math inline">\(0.01058\)</span> which is smaller than <span class="math inline">\(0.05\)</span>. therefore, we reject <span class="math inline">\(H_0\)</span> and conclude that there are statistically significant differences in the mean chlorophyll content between two groups.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Exercise 4.3
</div>
</div>
<div class="callout-body-container callout-body">
<p>If we don’t specify otherwise, the <code>t.test</code> routine assumes that the variances in the two groups, i.e., <span class="math inline">\(\sigma^2_x\)</span> and <span class="math inline">\(\sigma^2_y\)</span>, are <strong>unequal</strong> and adjusts for it. If we know (or assume) that the variances are equal, we can utilize that to obtain higher degrees of freedom since there’s one less parameter to estimate.</p>
<p>Investigate if the variances are equal using a so-called <span class="math inline">\(\chi^2\)</span>-test. This is done in R using the <code>var.test</code> routine. Interpret the output!</p>
</div>
</div>
<p><strong>Hypotheses</strong>: <span class="math inline">\(H_0: \sigma^2_x = \sigma^2_y\)</span> vs.&nbsp;<span class="math inline">\(H_1: \sigma^2_x \neq \sigma^2_y\)</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">var.test</span>(Alger<span class="sc">$</span>Klorofyll <span class="sc">~</span> Alger<span class="sc">$</span>Grupp)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    F test to compare two variances

data:  Alger$Klorofyll by Alger$Grupp
F = 0.51386, num df = 5, denom df = 5, p-value = 0.4825
alternative hypothesis: true ratio of variances is not equal to 1
95 percent confidence interval:
 0.07190457 3.67222210
sample estimates:
ratio of variances 
         0.5138575 </code></pre>
</div>
</div>
<p><strong>Answer:</strong> The p-value of <span class="math inline">\(0.4825\)</span> is larger than <span class="math inline">\(0.05\)</span> and the 95% confidence interval is <span class="math inline">\([0.07190457, 3.67222210]\)</span>. We fail to reject <span class="math inline">\(H_0\)</span> and conclude that there is no significant difference between two variances.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Exercise 4.4
</div>
</div>
<div class="callout-body-container callout-body">
<p>Repeat the t-test assuming equal variances by adding <code>var.equal=TRUE</code> in the R routine. What are your conclusions now?</p>
</div>
</div>
<p><strong>Assumption</strong>: <span class="math inline">\(\sigma^2=\sigma^2_x = \sigma^2_y\)</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Alger<span class="sc">$</span>Klorofyll <span class="sc">~</span> Alger<span class="sc">$</span>Grupp, <span class="at">var.equal=</span><span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  Alger$Klorofyll by Alger$Grupp
t = -3.2089, df = 10, p-value = 0.009349
alternative hypothesis: true difference in means between group Ljus and group Mörker is not equal to 0
95 percent confidence interval:
 -11.154519  -2.012148
sample estimates:
  mean in group Ljus mean in group Mörker 
            13.10000             19.68333 </code></pre>
</div>
</div>
<p><strong>Answer:</strong> The p-value and 95% confidence interval gets smaller than the t-test without assuming equal variances. The p-value of this two sample t-test is <span class="math inline">\(0.009349\)</span> which is smaller than <span class="math inline">\(0.05\)</span>. therefore, we reject <span class="math inline">\(H_0\)</span> and conclude that there are statistically significant differences in the mean chlorophyll content between two groups.</p>
</section>
<section id="test-with-matched-data-paired-samples" class="level1 unnumbered">
<h1 class="unnumbered">5. Test with Matched Data (Paired Samples)</h1>
<blockquote class="blockquote">
<p>Measurements of nitrogen load have been taken during spring and summer in a number of ponds. If one wants to compare the nitrogen load between the two seasons, a reasonable model is “paired samples.”</p>
</blockquote>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"data/lab3_filer/dammar.RData"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(Dammar<span class="sc">$</span>N_belast_V, Dammar<span class="sc">$</span>N_belast_S,</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"nitrogen load"</span>,</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"season"</span>,</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">names =</span> <span class="fu">c</span>(<span class="st">"Spring"</span>,<span class="st">"Summer"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab3_student_report_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(Dammar<span class="sc">$</span>N_belast_V<span class="sc">-</span>Dammar<span class="sc">$</span>N_belast_S,</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"difference in nutrient load spring-summer"</span>)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">a=</span><span class="dv">0</span>,<span class="at">b=</span><span class="dv">0</span>,<span class="at">col=</span><span class="st">'blue'</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Lab3_student_report_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Model:</strong> Let <span class="math inline">\(D\)</span> be the difference in measurements between spring and summer for a pond. The random variable <span class="math inline">\(D\)</span> has mean <span class="math inline">\(\mu\)</span> and variance <span class="math inline">\(\sigma^2\)</span>. We create a sample <span class="math inline">\((d_1,...,d_n)\)</span> for differences in measurement values. The mean is estimated by the sample mean, <span class="math inline">\(\hat{\mu}=\bar{d}\)</span>. According to the central limit theorem, <span class="math inline">\(\bar{d} \overset{A}{\sim} N(\mu,\frac{\sigma}{\sqrt{n}})\)</span>.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Exercise 5.1
</div>
</div>
<div class="callout-body-container callout-body">
<p>Is there a difference in means between spring and summer?</p>
<p>We test it with the following <strong>hypotheses:</strong> <span class="math inline">\(H_0: \mu = 0\)</span> vs.&nbsp;<span class="math inline">\(H_1: \mu \neq 0\)</span></p>
<p>This is a common test, and one does not need to calculate a new sample. To inform <code>t.test</code> that the data is matched in pairs, one adds <code>paired=TRUE</code> as an argument.</p>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Dammar<span class="sc">$</span>N_belast_V, Dammar<span class="sc">$</span>N_belast_S, <span class="at">paired=</span><span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  Dammar$N_belast_V and Dammar$N_belast_S
t = 1.2189, df = 7, p-value = 0.2624
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
 -19.49477  60.97227
sample estimates:
mean difference 
       20.73875 </code></pre>
</div>
</div>
<p><strong>Answer</strong>: The p-value of the paired t-test is <span class="math inline">\(0.2624\)</span>, which is greater than <span class="math inline">\(0.05\)</span>. Therefore, we fail to reject the <span class="math inline">\(H_0\)</span> and conclude that there is no significantly statistical difference in means between spring and summer.</p>
<section id="answers-to-some-of-the-questions-in-this-section" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="answers-to-some-of-the-questions-in-this-section">Answers to Some of the Questions in This Section:</h2>
<ol type="1">
<li>Answer<br>
3.2 A: p-value<span class="math inline">\(=0.033\)</span>; B: p-value<span class="math inline">\(=0.081\)</span>; We can detect a difference for A but not for B. 95% confidence intervals: A: <span class="math inline">\((42.06,\,42.94)\)</span>; B: <span class="math inline">\((35.69,\,42.51)\)</span><br>
4.3 The variances are not different (p-value<span class="math inline">\(=0.48\)</span>)<br>
4.4 t-test: p-value<span class="math inline">\(=0.009\)</span>; We can detect a difference in chlorophyll.<br>
5.1 p-value<span class="math inline">\(=0.262\)</span> We cannot detect any difference.</li>
</ol>
</section>
</section>
<section id="had-our-activation-program-an-effect" class="level1 unnumbered">
<h1 class="unnumbered">6. Had our activation program an effect?</h1>
<section id="problem-specification-in-the-study" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="problem-specification-in-the-study">Problem specification in the study</h2>
<p>Most researchers believe that high cholesterol levels in the blood are a risk factor for heart and vascular diseases. In a study, we wanted to investigate whether a multi-factor activation program (smoking cessation, mental, and physical training) could reduce cholesterol levels. We started with a group of 40 smoking men, all of whom had slightly elevated blood cholesterol levels. From these 40, we randomly selected 20 (Group A) to undergo our activation program.</p>
<p>The remaining 20 (Group B) continued with their usual lifestyle, at least as far as we perceived it. After six months, we measured the cholesterol levels (mmol/l) in all 40 men again.</p>
<p>In the file <code>blodprov.Rdata</code> there is data with the variables ´Afore´, ´Aefter´, ´Bfore´ and ´Befter´.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"./data/lab3_filer/blodprov.Rdata"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="questions" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="questions">Questions</h2>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Question 6.1
</div>
</div>
<div class="callout-body-container callout-body">
<p>Since we randomly selected the 20 individuals to undergo the activation program, there should be no differences between Group A and Group B regarding average cholesterol levels <strong>before</strong> the study begins. However, we want to ensure this explicitly so that we do not introduce a systematic difference between the groups from the start.</p>
<p>Is there a difference between the groups? Investigate with a suitable statistical test.</p>
</div>
</div>
<p><strong>Model:</strong> Let <span class="math inline">\(X\)</span> be the cholesterol levels of group A before the study with mean <span class="math inline">\(\mu_x\)</span> and variance <span class="math inline">\(\sigma_x^2\)</span>, and <span class="math inline">\(Y\)</span> be the cholesterol levels of group B before the study with mean <span class="math inline">\(\mu_y\)</span> and variance <span class="math inline">\(\sigma_y^2\)</span>. The means are estimated by sample means <span class="math inline">\(\hat \mu_x = \bar x\)</span> and <span class="math inline">\(\hat \mu_y = \bar y\)</span>. According to the central limit theorem, <span class="math inline">\(\bar{x} \overset{A}{\sim} N(\mu_x,\frac{\sigma_x}{\sqrt{n_x}})\)</span>.</p>
<p><strong>Hypotheses:</strong> <span class="math inline">\(H_0: \mu_x = \mu_y\)</span>, <span class="math inline">\(H_1: \mu_x \neq \mu_y\)</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(kolesterol<span class="sc">$</span>Afore, kolesterol<span class="sc">$</span>Bfore)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  kolesterol$Afore and kolesterol$Bfore
t = -1.342, df = 32.313, p-value = 0.189
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -0.33605384  0.06905384
sample estimates:
mean of x mean of y 
   6.3400    6.4735 </code></pre>
</div>
</div>
<p>The p-value of the two sample t-test is <span class="math inline">\(0.189\)</span>, which is greater than <span class="math inline">\(0.05\)</span>. Therefore, we fail to reject <span class="math inline">\(H_0\)</span> and conclude that there is no significant difference in average initial cholesterol levels between two groups.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Question 6.2
</div>
</div>
<div class="callout-body-container callout-body">
<p>Has the expected cholesterol level decreased in Group A? Investigate with a suitable statistical test.</p>
</div>
</div>
<p><strong>Model:</strong> Let <span class="math inline">\(D\)</span> be the difference in cholesterol level before and after the study. The random variable <span class="math inline">\(D\)</span> has mean <span class="math inline">\(\mu\)</span> and variance <span class="math inline">\(\sigma^2\)</span>. We create a sample <span class="math inline">\((d_1,...,d_n)\)</span> for differences in measurement values. The mean is estimated by the sample mean, <span class="math inline">\(\hat{\mu}=\bar{d}\)</span>. According to the central limit theorem, <span class="math inline">\(\bar{d} \overset{A}{\sim} N(\mu,\frac{\sigma}{\sqrt{n}})\)</span>.</p>
<p><strong>Hypotheses:</strong> <span class="math inline">\(H_0: \mu = 0\)</span>, <span class="math inline">\(H_1: \mu \neq 0\)</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(kolesterol<span class="sc">$</span>Aefter, kolesterol<span class="sc">$</span>Afore, <span class="at">paired=</span><span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  kolesterol$Aefter and kolesterol$Afore
t = -7.2472, df = 19, p-value = 7.042e-07
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
 -0.7597513 -0.4192487
sample estimates:
mean difference 
        -0.5895 </code></pre>
</div>
</div>
<p>The p-value of the paired t-test is <span class="math inline">\(7.042 \times 10^{-7}\)</span>, which is smaller than <span class="math inline">\(0.05\)</span>. We reject <span class="math inline">\(H_0\)</span> and conclude that there is a significant difference in cholesterol levels of group A before and after the study.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Question 6.3
</div>
</div>
<div class="callout-body-container callout-body">
<p>It is not unlikely that patients in Group B, even though they do not undergo the activation program, may still be affected in their cholesterol levels because attention to the issues may have an effect (a placebo effect).</p>
<p>Does this seem to be the case in our study? Study if there is a difference in cholesterol levels in patients in group B before and after the program. Investigate with a suitable statistical test.</p>
</div>
</div>
<p><strong>Model:</strong> Let <span class="math inline">\(D\)</span> be the difference in cholesterol level before and after the study. The random variable <span class="math inline">\(D\)</span> has mean <span class="math inline">\(\mu\)</span> and variance <span class="math inline">\(\sigma^2\)</span>. We create a sample <span class="math inline">\((d_1,...,d_n)\)</span> for differences in measurement values. The mean is estimated by the sample mean, <span class="math inline">\(\hat{\mu}=\bar{d}\)</span>. According to the central limit theorem, <span class="math inline">\(\bar{d} \overset{A}{\sim} N(\mu,\frac{\sigma}{\sqrt{n}})\)</span>.</p>
<p><strong>Hypotheses:</strong> <span class="math inline">\(H_0: \mu = 0\)</span>, <span class="math inline">\(H_1: \mu \neq 0\)</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(kolesterol<span class="sc">$</span>Befter, kolesterol<span class="sc">$</span>Bfore, <span class="at">paired=</span><span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  kolesterol$Befter and kolesterol$Bfore
t = 1.5231, df = 19, p-value = 0.1442
alternative hypothesis: true mean difference is not equal to 0
95 percent confidence interval:
 -0.05107043  0.32407043
sample estimates:
mean difference 
         0.1365 </code></pre>
</div>
</div>
<p>The p-value of the paired t-test is <span class="math inline">\(0.1442\)</span>, which is greater than <span class="math inline">\(0.05\)</span>. We fail to reject <span class="math inline">\(H_0\)</span> and conclude that there is no significant difference in cholesterol levels of group B before and after the study.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Question 6.4
</div>
</div>
<div class="callout-body-container callout-body">
<p>Did the activation program reduce the expected cholesterol level in Group A? Investigate with a suitable statistical test if the activation program affects the two groups differently?</p>
</div>
</div>
<p><strong>Model:</strong> Let <span class="math inline">\(D\)</span> be the difference in cholesterol level before and after the study. The random variable <span class="math inline">\(D\)</span> has mean <span class="math inline">\(\mu\)</span> and variance <span class="math inline">\(\sigma^2\)</span>. We create a sample <span class="math inline">\((d_1,...,d_n)\)</span> for differences in measurement values. The mean is estimated by the sample mean, <span class="math inline">\(\hat{\mu}=\bar{d}\)</span>. According to the central limit theorem, <span class="math inline">\(\bar{d} \overset{A}{\sim} N(\mu,\frac{\sigma}{\sqrt{n}})\)</span>.</p>
<p><strong>Hypotheses:</strong> <span class="math inline">\(H_0: \mu = 0\)</span>, <span class="math inline">\(H_1: \mu &lt; 0\)</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(kolesterol<span class="sc">$</span>Aefter, kolesterol<span class="sc">$</span>Afore, <span class="at">paired=</span><span class="cn">TRUE</span>, <span class="at">alternative =</span> <span class="st">"less"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Paired t-test

data:  kolesterol$Aefter and kolesterol$Afore
t = -7.2472, df = 19, p-value = 3.521e-07
alternative hypothesis: true mean difference is less than 0
95 percent confidence interval:
       -Inf -0.4488484
sample estimates:
mean difference 
        -0.5895 </code></pre>
</div>
</div>
<p>The p-value of the one-sided paired t-test is <span class="math inline">\(3.521 \times 10^{-7}\)</span>, which is smaller than <span class="math inline">\(0.05\)</span>. We reject <span class="math inline">\(H_0\)</span> and conclude that there is a significant decrease in cholesterol levels of group A before and after the study.</p>
<p><strong>Model:</strong> Let <span class="math inline">\(D_A\)</span> be the difference in cholesterol level before and after the study of group A with mean <span class="math inline">\(\mu_A\)</span> and variance <span class="math inline">\(\sigma_A^2\)</span>, and <span class="math inline">\(D_B\)</span> be the difference in cholesterol level before and after the study of group B with mean <span class="math inline">\(\mu_B\)</span> and variance <span class="math inline">\(\sigma_B^2\)</span>. The means are estimated by the sample means <span class="math inline">\(\hat{\mu_A}=\bar{d_A}\)</span> and <span class="math inline">\(\hat{\mu_B}=\bar{d_B}\)</span>. According to the central limit theorem, <span class="math inline">\(\bar{d_A} \overset{A}{\sim} N(\mu_A,\frac{\sigma_A}{\sqrt{n_A}})\)</span> and <span class="math inline">\(\bar{d_B} \overset{A}{\sim} N(\mu_B,\frac{\sigma_B}{\sqrt{n_B}})\)</span>.</p>
<p><strong>Hypotheses:</strong> <span class="math inline">\(H_0: \mu_A = \mu_B\)</span>, <span class="math inline">\(H_1: \mu_A \neq \mu_B\)</span></p>
</section>
<section id="instruction-for-reporting" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="instruction-for-reporting">Instruction for reporting</h2>
<p>Please specify (if appropriate):</p>
<ul>
<li><p>what assumptions you make about data,</p></li>
<li><p>which models you are specifying,</p></li>
<li><p>which hypothesis you use,</p></li>
<li><p>which theorems you use.</p></li>
<li><p>Present the results of the analysis and what interpretations and conclusions you make.</p></li>
<li><p>To pass task 6, avoid referring to the R-code to describe what you have done.</p></li>
</ul>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>